AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  netlify-cms-aws
Transform:
- AWS::Serverless-2016-10-31

Resources:

  netlifyCMSAuthRedirect2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: redirect.handler
      CodeUri: src/auth/
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 3
      Description: >-
        An AWS Lambda function for authorizing Netlify CMS through GitHub.
        Intended as a proxy function triggered via API Gateway.
        Followed by netlify-cms-auth-token-handler.
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /auth
            Method: get
            # RestApiId:

  netlifyCMSAuthTokenHandler2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: token-handler.handler
      CodeUri: src/auth/
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 3
      Description: >-
        An AWS Lambda function for authorizing Netlify CMS through GitHub.
        Intended as a proxy function triggered via API Gateway.
        Preceded by netlify-cms-auth-redirect.
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /callback
            Method: get
            # RestApiId:
